services:
  student-grade-predictor-env:
    image: jiroamato/student_grade_predictor:d4b334b
    ports:
      - "8888:8888"
    volumes:
      - .:/workplace
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64