name: 'student-grade-predictor'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pip=25.3
  - ipykernel=7.1.0
  - nb_conda_kernels=2.5.1
  - altair-all=5.4.1
  - conda-lock=3.0.4
  - vega_datasets=0.9.0
  - jupyterlab=4.5.0
  - scipy=1.16.3
  - matplotlib=3.10.8
  - scikit-learn=1.7.2
  - requests=2.32.5
  - eli5=0.16.0
  - jinja2=3.1.6
  - pandera=0.27.0
  - deepchecks=0.3.2
  - pip:
    - altair_ally==0.1.1
