name: student_grade_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - vegafusion
  - altair
  - scikit-learn
  - pandas
  - python=3.11
  - vegafusion-jupyter
  - notebook
  - requests
  - jupyter
  - jupyter_contrib_nbextensions
