name: 'student-grade-predictor'
channels:
  - conda-forge
dependencies:
  - conda=25.11.0 
  - python=3.12.12
  - pip=25.3
  - ipykernel=7.1.0
  - click=8.3.1
  - jupyterlab=4.5.0
  - ipython=8.12
  - numpy=1.26.4  
  - nb_conda_kernels=2.5.1
  - altair-all=5.4.1
  - conda-lock=3.0.4
  - vega_datasets=0.9.0
  - scipy=1.16.3
  - matplotlib=3.10.7
  - scikit-learn=1.7.2
  - requests=2.32.5
  - eli5=0.16.0
  - jinja2=3.1.6
  - make=4.4.1
  - pip:
    - altair_ally==0.1.1
    - deepchecks==0.19.1
    - pandera==0.27.0 
    - python-json-logger==2.0.7
    - pytest==9.0.1
    - pytest-mock==3.15.1
    - pytest-cov==7.0.0
    - quarto-cli==1.8.26